declare var THREE: any;

declare var MAP: number[][];
declare var WORLD_MODS: any;
declare var WORLD_TILE_DEFS: any;
declare var TREE_MODS: any;
declare var HOUSE_MODS: any;
declare var WORLD_ITEMS: any;
declare var PLAYER_INV: any;
declare var NPCS: any;
declare var worldId: string;
declare var playerId: string;
declare var PLAYER_NICK: string;
declare var ONLINE_PLAYERS: any;
declare var INITIAL_CHAT: any;
declare var INITIAL_DM_INDEX: any;
declare var INIT_ROW: number;
declare var INIT_COL: number;
declare var INIT_SEQ: number;
declare var INIT_ROTATION: number;
declare var ITEM_REGISTRY: any;
declare var LIVING_REGISTRY: any;
declare var WORLD_CLASS_REGISTRY: Array<{
  id: string;
  baseType: string;
  rows: number;
  cols: number;
  labelKey: string;
  fallbackLabel: string;
}>;
declare var INITIAL_FOLLOW: { target_id: string; target_label: string } | null;
